version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
  
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip python2.7 python-pip -y
      - run:
          name: Install awscli
          command: |
             sudo pip install awscli
             aws configure set default.region us-east-1
      - run:
          name: Build Artifact
          command: |
             cd Lambda
             pwd
             ls -al
             mvn clean install
             cd target/
             ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp --recursive Lambda-0.0.1-SNAPSHOT.jar s3://${CODE_DEPLOY_S3_BUCKET}

      - run:
          name: Email Lambda function
          command: |
            cd target
            ls -al
            aws lambda update-function-code --function-name=SendEmailOnSNS --zip-file=fileb://Lambda-0.0.1-SNAPSHOT.jar
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master